import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "boxicons/css/boxicons.min.css";
import LayoutWraper from "./layout-wraper";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@/components/theme-context";
import { LoadingProvider } from "@/components/loading-context";
import Loading from "@/components/loading";

import { Toaster } from "@/components/ui/sonner";
import { AlertDialogProvider } from "@/components/alert-confirm";
import Configs from "@/lib/config";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: Configs.app_name,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster position="top-right" richColors={true} closeButton visibleToasts={4} />
          <SessionProvider>
            <LoadingProvider>
              <Loading />
              <AlertDialogProvider>
                <LayoutWraper children={children} />
              </AlertDialogProvider>
            </LoadingProvider>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
